Repository sebs-scholarship/Website, pull requests merged in 2019-08, with the labels that each got.

#2 Shifted header left and fixed mobile compatibility issue
  index.html
Labels: bug, enhancement

#4 Changed Styling, Added Content, Updated Assets
  assets/css/style.css
  assets/images/2017-min.jpg
  assets/images/college-min.jpg
  assets/images/college.jpg
  assets/images/graduation-min.jpg
  assets/images/graduation.jpg
  assets/images/writing-min.jpg
  assets/images/writing.jpg
  assets/js/jquery.min.js
  index.html
Labels: enhancement

#13 Changed navigation bar behavior
  assets/js/main.js
  index.html
Labels: bug
