Repository sebs-scholarship/Website, pull requests merged in 2020-05, with the labels that each got.

#67 Added feedback form and changed header button
  feedback/index.html
  index.html
Labels: enhancement, functional, graphical

#68 Changed wording
  index.html
Labels: enhancement, graphical

#69 Fixed learn more issue causing navbar to open
  index.html
Labels: bug, functional

#70 Added past recipients section and updated with our recipient
  assets/css/style.css
  assets/images/Marianna.jpg
  index.html
Labels: enhancement, functional, graphical

#72 Jekyll Migration
  .github/workflows/main.yml
  .github/workflows/test.yml
  .gitignore
  Gemfile
  _config.yml
  _includes/analytics.html
  _layouts/default.html
  _layouts/redirect.html
  apply/index.html
  donate/index.html
  email/confirm.html
  email/invalid.html
  email/not-subscribed.html
  email/subscribe.html
  email/subscribed.html
  email/success.html
  email/unsubscribe.html
  email/unsubscribed.html
  feedback/index.html
  forbidden.html
  index.html
  missing.html
  privacy_policy.html
  selection-process/index.html
  selection_process.html
  sitemap.xml
  subscribe/index.html
  tax_documents.html
  volunteer/index.html
Labels: enhancement, functional, on hold, optimization

#73 Feature/button
  assets/images/2017-alt-min.jpg
  index.html
Labels: enhancement, functional, optimization

#74 Migrate to Jekyll
  .github/workflows/main.yml
  .github/workflows/test.yml
  .gitignore
  Gemfile
  _config.yml
  _includes/analytics.html
  _layouts/default.html
  _layouts/redirect.html
  apply/index.html
  assets/images/2017-alt-min.jpg
  donate/index.html
  email/confirm.html
  email/invalid.html
  email/not-subscribed.html
  email/subscribe.html
  email/subscribed.html
  email/success.html
  email/unsubscribe.html
  email/unsubscribed.html
  feedback/index.html
  forbidden.html
  index.html
  missing.html
  privacy_policy.html
  selection-process/index.html
  selection_process.html
  sitemap.xml
  subscribe/index.html
  tax_documents.html
  volunteer/index.html
Labels: enhancement, functional, graphical, optimization
