Repository sebs-scholarship/Website, pull requests merged in 2020-06, with the labels that each got.

#77 GSuite Migration Update
  email/contact.php
  index.html
Labels: enhancement, functional

#84 Migration to Bootstrap v4.5
  _layouts/default.html
  assets/css/bootstrap/bootstrap-grid.min.css
  assets/css/bootstrap/bootstrap-reboot.min.css
  assets/css/bootstrap/bootstrap.min.css
  assets/css/style.css
  assets/css/style.css.map
  assets/js/bootstrap.min.js
Labels: functional, graphical, optimization

#85 Migrate Contact Form and Bootstrap
  _layouts/default.html
  assets/css/bootstrap/bootstrap-grid.min.css
  assets/css/bootstrap/bootstrap-reboot.min.css
  assets/css/bootstrap/bootstrap.min.css
  assets/css/style.css
  assets/css/style.css.map
  assets/js/bootstrap.min.js
  email/contact.php
Labels: enhancement, functional, optimization
